#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx eslint src/**/*.ts
npx prettier --check src/**/*.ts
npx jest --ci --coverage --passWithNoTests --runInBand --coverageReporters=text
npx tsc -p tsconfig.build.json --noEmit
